export const ar = {
  hello: "اهلا",
  Register: "سجل ",
  FirstName: "الاسم الاول",
  LastName: "الاسم الاخير",
  MobileNumber: "رقم الهاتف",
//   address: "العنوان",
  Role: "الدور",
  WhatsAppNumber: "رقم الواتس اب",
  CompanyName: "اسم الشركة",
  Password: "الرقم السرى",
  ConfirmPassword: "تاكيد الرقم السرى",
  Work: "العمل",
  Description: "الوصف",
  Country: "البلد",
  Government: "المحافظة",
  Address: "العنوان",
  CompanyPhoneNumber: "رقم الشركة",
  CommercialRecord: "سجل تجارى",
  UploadCompanyLogo: "حمل لوجو الشركة",
  Optional: "اختياري",
  AcceptTermsOfServiceAndPrivacyPolicy:"قبول شروط الخدمة و الخصوصية",
  AlreadyHaveAnAccount:"هل لديك حساب ؟",
  SignIn:"تسجيل الدخول",
  Email:"البريد الالكتروني",
  Job:"الوظيفة",
  CompanyMail:"البريد الالكتروني للشركة",
  CompanyWebsite:"موقع الشركة",
  Company:"شركة",
  Individual:"فرد",
	language: "العربيه",
	hello: "اهلا",
};
