export const ar = {
	language: "العربيه",
	registration: {
		register: "تسجيل ",
		createAnAccount: "انشاء حساب جديد",
		firstName: "الاسم الاول",
		lastName: "الاسم الاخير",
		mobileNumber: "رقم الهاتف",
		role: "الدور",
		whatsAppNumber: "رقم الواتس اب",
		companyName: "اسم الشركة",
		password: "الرقم السرى",
		confirmPassword: "تاكيد الرقم السرى",
		work: " العمل / الحقل",
		field: "المجال",
		description: "الوصف",
		country: "البلد",
		governorate: "المحافظة",
		address: "العنوان",
		companyPhoneNumber: "رقم الشركة",
		commercialRecord: "سجل تجارى",
		commercialRecordOptional: " (اختياري)سجل تجارى",
		uploadCompanyLogo: "حمل لوجو الشركة (اختياري)",
		optional: "اختياري",
		acceptTermsOfServiceAndPrivacyPolicy: "قبول شروط الخدمة و الخصوصية",
		alreadyHaveAnAccount: "هل لديك حساب ؟",
		signIn: "تسجيل الدخول",
		email: "البريد الالكتروني",
		job: "الوظيفة",
		companyMail: "البريد الالكتروني للشركة (اختياري)",
		companyWebsite: "موقع  الالكتروني الشركة",
		companyWebsiteOptional: "موقع الالكتروني للشركة (اختياري)",
		company: "شركة",
		individual: "فرد",
		buyer: "مشترى",
		Contractor: "مقاول",
		admin: "المسؤل",
		employee: "موظف",
		Supplier: "مورد",
		userType: "نوع المستخدم",
		organisationLegalStructure: "نوع الشركة القنوني",
		pleaseChooseCountryFirst: "برجاء اختيار البلد اولا",
		pleaseFillAllRequiredFields: "برجاء املئ جميع الخانات *",
		pleaseFillFirstName: "* برجاء املئ الاسم الاخير",
		pleaseFillLastName: "* برجاء املئ الاسم الاخير",
		pleaseChooseCompanyName: "* برجاء اختار اسم الشركة",
		pleaseChooseWork: "* برجاء اختار مجالات العمل ",
		pleaseFillmobileNumber: "* برجاء املئ رقم الهاتف ",
		pleaseFillEmail: "* برجاء املئ  البريد الالكتروني ",
		pleaseFillPassword: "* برجاء املئ كلمة السر ",
		pleaseFillConfirmPassword: "* برجاء املئ تأكيد كلمة السر ",
		pleaseChooseCompanyType: "* برجاء اختار نوع  الشركة ",
		pleaseFillCompanyWebsite: "* برجاء املئ موقع  الالكتروني للشركة",
		pleaseChooseCountry: "* برجاء اختار البلد",
		pleaseChooseGovernorate: "* برجاء اختار المحافظه",
		pleaseFillAddress: "* برجاء املئ العنوان ",
		pleaseUploadCommercialRecord: "* برجاء رفع سجل الشركة ",
		pleaseChooseYourRole: "* برجاء اختار الوظيفة  ",
	},
	footer: {
		copyRights: "٢٠٢١ شيك , كل الحقوق محفوظه",
	},
	navbar: {
		signin: "تسجيل الدخول",
		register: "تسجيل",
		requestRFQ: " طلب الاسعار",
		cart: "العربه",
		AllSuppliers: " كل الموردين",
		admin: "ادمن",
		logout: "تسجيل الخروج",
		viewProfile: "صفحتي",
		contactUs: "اتصل بنا",
	},
	suppliers: {
		suppliersGrid: {},
		suppliersFilter: {
			filter: "فلتر",
			category: "الفئه",
			location: "الموقع",
			products: "المنتجات",
			all: "الكل",
			inStock: "في المخزن",
			rate: "تقييم",
		},
		rateDetails: {
			amountOfWorkOpinion: "حجم العمل كام ؟",
			paymentFacilitiesOpinion: "شروط الدفع كانت مريحه ؟",
			relativePricesOpinion: "رأيك في الاسعار بالنسبه لاسعار السوق ؟",
			handlingWayOpinion: "رأيك في الاسعار بالنسبه لاسعار السوق ؟",
			timingOpinion: "الشغل خلص في الوقت المحدد ؟",
			workQualityOpinion: "رأيك في جوده الشغل ؟",
		},
	},
	login: {
		signin: "تسجيل الدخول",
		mobileNumber: "رقم الهاتف",
		email: "البريد الالكتروني",
		password: "الرقم المرور",
		forgetPassword: "هل نسيت كلمة المرور ؟",
		didHaveAnAcount: "هل لديك حساب ؟",
		registerNow: "سجل الان !",
		signInWithMobileNumber: "هل تريد التسجيل برقم الهاتف ؟",
		signInWithMobileEmail: "هل تريد التسجيل بالبريد الالكتروني ؟",
		confirmPassword: "تاكيد الرقم السرى",
		save: "حفظ",
		forgetPasswordTitle: "نسيت كلمة المرور",
		RememberYourPassword: "هل تتذكر كلمة المرور ؟",
		send: "ارسال",
		emailIsRequired: "البريد الالكترونى مطلوب",
		passwordIsRequired: " كلمة السر مطلوب",
		confirmPasswordIsRequired: " تأكيد كلمة السر مطلوبه",
		ResetPassword: " اعادة تعيين كلمة المرور",
		passwordConfirmationDoesnotMatch: "كلمة المرور غير متطابقه",
		mobileNumberIsRequired: "رقم الهاتف مطلوب",
		verifyYourMailNow: " تحقق من البريد الالكترونى",
	},
	profilePage: {
		completedPercentage: "٤٠٪ مكتمل",
		addMoreWork: "*اضف اعمال اخري لتوثيق حسابك",
		prevWork: "الاعمال السابقه",
		reject: "ارفض",
		accept: "اقبل",
	},
	offerTable: {
		name: "الاسم",
		company: "الشركة",
		price: "السعر",
		city: "المدينة",
		paymentRequired: "الدفعه المقدمة المطلوبة ",
		rating: "التقييم",
		volumeOfWorkFromShyeek: "حجم العمل في sheyyek",
		note: "ملاحظات",
		actionList: "قائمة العمل",
		delete: "حذف",
		acceptOffer: "قبول العرض",
		startConversation: "بدء المحادثة",
		makeOnlineSession: "بدء محادثه اون لاين",
	},
	buyerHome: {
		importExcelFile: "اضف من ملف اكسيل",
		addNewItem: "اضف بند جديد",
		ccCollugues: "شارك زملائك",
		item: "البند",
		description: "الوصف",
		unit: "الوحده",
		quantity: "الكميه",
		preferredBrands: "العملات التجاريه المفضله",
		categories: "التصنيف",
		includeInstallation: "شامل التركيب",
		notes: "ملحوظات",
		selectCategory: "اختر نوع المنتج",
		category: "المنتج",
		installAll: "تركيب الكل",
		deliveredTo: "توصيل الي",
		companyWarehouse: "مستودع الشركه",
		projectLocation: "مكان المشروع",
		address: "العنوان",
		deadlineRecievingOffers: "تاريخ انتهاء تلقي العروض",
		deliveryDate: "تاريخ التوصيل",
		confirm: "تأكيد",
		selectDate: "اختر التاريخ",
		invitedByEmail: "مدعوين عن طريق البريد الالكتروني",
		addNewEmail: "اضف بريد الكتروني جديد",
		publishToNetwork: "انشر علي شبكه موردي شيك ذات الصله",
		revealPrices: "اظهار الاسعار للمنافسين",
		postRFQ: "ارسل طلب السعر",
		selectSupplierEmail: "اختر البريد الالكتروني للمورد",
		newItemAdded: "تم اضافه بند جديد",
		projectName: "اسم المشروع",
		invite: "ارسل دعوه",
		addValidEmail: "من فضلك اضف بريد الكرتوني صحيح",
		addEmail: "اضف",
		postRFQAlert:
			"من فضلك حدد اسماء الموردين و المقاولين اللي عايز تدعوهم لملء طلب السعر",
		RFQs: "طلبات الاسعار ",
		NoOfQuotations: "عدد الاقتباسات",
		deadline: "معاد التسليم",
		minPrice: "الحد الادني للسعر",
		maxPrice: "الحد الاقصي للسعر",
		edite: "تعديل",
		viewProfile: "عرض الملف الشخصي",
		delete: "حذف",
		addRfq: "اضف عرض سعر جديد",
		noRFQs: "لا يوجد عروض اسعار",
		noCompanies: "لا يوجد شركات تطابق مجالات عملك",
		toSeeCompanies: "يمكنك تعديل عملك / مجالك لرؤية الشركات ذات الصلة",
		relatedMarketPlace: "الشركات ذات الصلة",
	},
	supplierHome: {
		addNewProduct: "أضف منتج جديد",
		drafts: "مسودات",
		addPriceList: "أضف قائمه اسعار",
		save: "حفظ",
		cancel: "الغاء",
		pleaseUploadExcel: "من فضلك ارفع ملف اكسيل",
		addProductSuccess: "طلب اضافه المنتجات الخاص بك قيد التنفيذ",
		ok: "تم",
		specs: "المواصفات",
		saveAndAdd: "احفظ و اضف اخر",
		productName: "اسم المنتج",
		price: "السعر",
		addDifferentSizes: "اضف احجام مختلفه",
		addDifferentModels: "اضف انواع مختلفه",
		availableQuantity: "الكميه المتوفره في المخازن",
		add: "اضف",
		pleaseAddPhoto: "من فضلك اضف صوره ",
		pleaseAddSpecs: "من فضلك اضف المواصفات",
		pleaseAddName: "من فضلك اضف الاسم",
		pleaseAddPrice: "من فضلك اضف السعر",
		rfqInvitations: "دعوات طلبات السعر",
		pleaseAddQty: "من فضلك اضف الكميه",
		noOfQuotations: "عدد العروض المنافسه",
		deadline: "تاريخ انتهاء استقبال الطلبات",
		maxPrice: "السعر الاعلي",
		minPrice: "السعر الادني",
		fillSheet: "قم بتقديم سعرك ",
		productDetails: "تفاصيل المنتج",
		edit: "تعديل",
		delete: "الغاء",
	},
	home: {
		shayek: "شيّك",
		live: "مباشر",
		noResultFound: "لا توجد نتيجة",
		tryAnotherKeyword: "حاول كلمة اخري",
		today: "اليوم",
		Updated: "اخر تحديث لبضاعة المخزن",
		optimizingProcurement: "تحسين عملية المشتريات. ",
		verifiedConnectedStreamlined: "معتمدة و سلسة و أكثر اتصالاً",
		procurementManagement: "نجعل إدارة المشتريات عملية",
		email: "البريد الالكتروني",
		name: "الاسم",
		mobile: "رقم الهاتف",
		msg: "رسالة",
		nameIsRequired: "الاسم مطلوب",
		mobileNumberIsRequired: "رقم الهاتف مطلوب",
		messageIsRequire: "الرسالة مطلوبه",
		yourMessageSentSuccessfully: "رسالتك ارسلت بنجاح",
		yourMessageSentnotSuccessfully: "رسالتك لم ترسل بنجاح",
		sendMessage: "ارسل الرسالة",
		getInTouch: "تواصل معانا",
		dropUsANoteBelow: "اترك لنا ملاحظه",
		valueProposition: "قيمة الموقع",
		transparency: "الشفافية",
		contentOfTransparency:
			"دائمًا في نسبة مخاطره عند التعاقد مع موردين و مقاولين جدد و تقييم سابقه أعمالهم و عروضهم الفنيه و الماليه. نظرة عامه شامله للأسعار الشبيهة في السوق و تقييمات الموردين و المقاولين المماثلين تجعل عملية اتخاذ القرار أكثر سلاسة من أي وقت مضى.",
		accountability: "المسؤلية",
		contentOfAcountability:
			"السوق كبير و مليء بالمقاولين والموردين المختلفين، لا يوجد قاعدة بيانات محدثة باستمرار لأداء المقاول أو المورد و كذلك المشتري. نلتزم بتقديم أفضل تجربة شراء لك من خلال التحسين المستمر لشبكة الموردين و الأدوات التقنية للمنصة.",
		optimizedProcess: "عملية مشتريات مُحسّنة",
		contentOfoptimizedProcess:
			"عملية البحث ثم التقييم ثم التفاوض ثم اتخاذ القرار عملية شاقة تستغرق وقت طويل و غالبًا تحتاج إلى تكرارها عدة مرات أثناء المشروع بدون معلومات داعمة كافية من السوق. ربط جميع الأطراف من خلال منصة مُميكنة يؤدي إلي زيادة الموثوقية مع توفير الوقت والتكلفة.",
	},
};
