export const ar = {
  language: "العربيه",
  registration: {
    register: "تسجيل ",
    createAnAccount: "انشاء حساب جديد",
    firstName: "الاسم الاول",
    lastName: "الاسم الاخير",
    mobileNumber: "رقم الهاتف",
    role: "الدور",
    whatsAppNumber: "رقم الواتس اب",
    companyName: "اسم الشركة",
    password: "الرقم السرى",
    confirmPassword: "تاكيد الرقم السرى",
    work: "العمل",
    description: "الوصف",
    country: "البلد",
    government: "المحافظة",
    address: "العنوان",
    companyPhoneNumber: "رقم الشركة",
    commercialRecord: "سجل تجارى",
    uploadCompanyLogo: "حمل لوجو الشركة",
    optional: "اختياري",
    acceptTermsOfServiceAndPrivacyPolicy: "قبول شروط الخدمة و الخصوصية",
    alreadyHaveAnAccount: "هل لديك حساب ؟",
    signIn: "تسجيل الدخول",
    email: "البريد الالكتروني",
    job: "الوظيفة",
    companyMail: "البريد الالكتروني للشركة",
    companyWebsite: "موقع الشركة",
    company: "شركة",
    individual: "فرد",
    buyer: "المشتري",
	Contractor:"البناء"
	
  },
  footer: {
	copyRights: "٢٠٢١ شيك , كل الحقوق محفوظه",
},
};
