export const en = {
	language: "English",
	registration: {
		register: "Register ",
		createAnAccount: "Create An Account",
		firstName: "First Name",
		lastName: "Last Name",
		mobileNumber: "Mobile Number",
		role: "Role",
		whatsAppNumber: "WhatsApp Number",
		companyName: "Company Name",
		password: "Password",
		confirmPassword: "Confirm Password",
		work: "Work / Field",
		field: "Field",
		description: "Description",
		country: "Country",
		governorate: "Government",
		address: "Address",
		companyPhoneNumber: "Company Phone Number",
		commercialRecord: "Commercial Record ",
		uploadCompanyLogo: "Upload Company Logo( Optional )",
		optional: "Optional",
		acceptTermsOfServiceAndPrivacyPolicy:
			"Accept Terms of Service and Privacy Policy",
		alreadyHaveAnAccount: "Already Have An Account?",
		signIn: "Sign In",
		email: "Email",
		job: "Job",
		companyMail: "Company Mail ( Optional )",
		companyWebsite: "Company Website",
		companyWebsiteOptional: "Company Website (Optional)",
		company: "Company",
		individual: "Individual",
		buyer: "Buyer",
		Contractor: "Contractor",

		admin: "Admin",
		employee: "Employee",
		Supplier: "Supplier",
		userType: "User type",
		commercialRecordOptional: "commercialRecord (Optional)",
		organisationLegalStructure: "Organisation Legal Structure",
		pleaseChooseCountryFirst: "please Choose Country First",
		PleaseFillAllRequiredFields: "please Fill All Required Fields *",
		pleaseFillFirstName: "* Please fill firstName",
		pleaseFillLastName: "* Please fill lastName",
		pleaseChooseCompanyName: "* please Choose CompanyName",
		PleaseChooseWork: "* Please Choose Work",
		pleaseFillmobileNumber: "* please Fill mobileNumber",
		pleaseFillEmail: "* please Fill Email",
		pleaseFillPassword: "* please Fill Password",
		pleaseFillConfirmPassword: "* please Fill Confirm Password",
		pleaseChooseCompanyType: "* Please Choose Company Type",
		pleaseFillCompanyWebsite: "* please Fill CompanyWebsite",
		pleaseFillCountry: "* please Fill Country",
		pleaseChooseGovernorate: "* Please Choose Governorate",
		pleaseFillAddress: "* please Fill Address",
		pleaseUploadCommercialRecord: "* please Upload CommercialRecord",
		pleaseChooseYourRole: "* please Choose Your Role  ",
	},
	footer: {
		copyRights: "2021 Shayyek. All Rights Reserved",
	},

	navbar: {
		signin: "Sign in",
		register: "Register",
		requestRFQ: "Request RFQ",
		cart: "Cart",
		AllSuppliers: "All Suppliers",
		admin: "Admin",
		logout: "Logout",
		viewProfile: "View Profile",
		contactUs: "Contact Us",
	},
	suppliers: {
		suppliersGrid: {},
		suppliersFilter: {
			filter: "Filter",
			category: "Category",
			location: "Location",
			products: "Products",
			all: "All",
			inStock: "In Stock",
			rate: "Rate",
		},
		rateDetails: {
			amountOfWorkOpinion: "Volume of work ?",
			paymentFacilitiesOpinion:
				"Payment terms compared to others? Do they need many payments in between?",
			relativePricesOpinion: "Prices compared to others?",
			handlingWayOpinion:
				"How was your experience? How was their service? Did they make many change-orders? ",
			timingOpinion: "Finished the job on time? Response time to requests?",
			workQualityOpinion: "Quality of work? Safety? Cleanliness? etc... ",
		},
	},
	login: {
		signin: "Sign in",
		mobileNumber: "Mobile Number",
		email: "Email",
		password: "Password",
		forgetPassword: "Forget Password ?",
		didHaveAnAcount: "Didn’t Have an acount ?",
		registerNow: "Register Now !",
		signInWithMobileNumber: "Sign in With Mobile Number ?",
		signInWithMobileEmail: "Sign in With E-mail ?",
		confirmPassword: "Confirm Password",
		save: "Save",
		forgetPasswordTitle: "forget Password ",
		RememberYourPassword: "Remember Your Password?",
		send: "Send",
		emailIsRequired: "Email is required",
		passwordIsRequired: "password is required",
		confirmPasswordIsRequired: "confirm Password is required",
		ResetPassword: "Reset Password",
		passwordConfirmationDoesnotMatch: "password confirmation doesn't match",
		mobileNumberIsRequired: "mobileNumber is required",
		verifyYourMailNow: "Verify your mail Now",
	},
	profilePage: {
		completedPercentage: "40% Completed",
		addMoreWork: "*Add More Previous Works To Verify Your Account",
		prevWork: "Previous work",
		reject: "Reject",
		accept: "Accept",
	},
	offerTable: {
		name: "Name",
		company: "Company",
		price: "Price",
		city: "City",
		paymentRequired: "Payment Required",
		rating: "Rating",
		volumeOfWorkFromShyeek: "Volume of work from Shyeek",
		note: "Note",
		actionList: "Action List",
		delete: "Delete",
		acceptOffer: "Accept Offer",
		startConversation: "Start Conversation",
		makeOnlineSession: "Make online session",
	},
	supplierHome: {
		addNewProduct: "Add New Product",
		drafts: "Drafts",
		addPriceList: "Add Price List",
		save: "Save",
		cancel: "Cancel",
		pleaseUploadExcel: "Please upload an Excel sheet",
		addProductSuccess: "Your request to add product is being processed",
		ok: "Ok",
		specs: "Specs",
		saveAndAdd: "Save & Add Another",
		productName: "Product name",
		price: "Price",
		addDifferentSizes: "Add different Sizes",
		addDifferentModels: "Add different Models",
		availableQuantity: "Available Quantity in stock",
		add: "Add",
		pleaseAddPhoto: "Please add a photo",
		pleaseAddSpecs: "Please add specs",
		pleaseAddPrice: "Please add price",
		pleaseAddName: "Please add a name",
		pleaseAddQty: "Please add quantity",
		rfqInvitations: "RFQ invitations",
		noOfQuotations: "No. of quotations",
		deadline: "deadline",
		maxPrice: "Max price",
		minPrice: "Min price",
		fillSheet: "Fill Sheet",
		productDetails: "Product details",
		edit: "Edit",
		delete: "Delete",
		noRFQs: "No RFQs",
		noProducts: "There are no products",
		youCanAddProducts: "You can add products to your marketplace",
		chooseSize: "Choose size",
		chooseModel: "Choose model",
		addToCart: "Add to Cart",
		quantity: "Quantity",
	},
	buyerHome: {
		importExcelFile: "Import Excel File",
		addNewItem: "Add New Item",
		ccCollugues: "CC Collugues",
		item: "Item",
		unit: "Unit",
		description: "Description",
		quantity: "Quantity",
		preferredBrands: "Preferred Brands",
		categories: "Categories",
		includeInstallation: "Include Installation",
		notes: "Notes",
		selectCategory: "Select Category",
		category: "Category",
		installAll: "Install all",
		deliveredTo: "Delivered To",
		companyWarehouse: "Company warehouse",
		projectLocation: "Project location",
		address: "Address",
		deadlineRecievingOffers: "Deadline recieving offers",
		deliveryDate: "Delivery date",
		confirm: "Confirm",
		selectDate: "Select Date",
		invitedByEmail: "Invited by E-mail",
		addNewEmail: "Add new email",
		publishToNetwork: "Publish to relevant Shayyek suppliers network",
		revealPrices: "Reveal prices to bidders",
		postRFQ: "Post RFQ",
		selectSupplierEmail: "Select supplier E-mail",
		newItemAdded: "New item added",
		projectName: "Project name",
		invite: "Invite",
		addValidEmail: "Please add a valid email",
		addEmail: "Add email",
		postRFQAlert:
			"Please choose suppliers & contractors you want to share RFQ with.",
		RFQs: "RFQs",
		NoOfQuotations: "No. of quotations",
		deadline: "Deadline",
		minPrice: "Min Price",
		maxPrice: "Max Price",
		edite: "Edite",
		viewProfile: "View Profile",
		delete: "Delete",
		addRfq: "Add New RFQ",
		noRFQs: "No RFQs",
		noCompanies: "No companies match your interests",
		toSeeCompanies: "you can edit your work/field to see related companies",
		relatedMarketPlace: "Related MarketPlace",
	},
	home: {
		shayek: "Shayyek",
		noResultFound: "No Result Found",
		tryAnotherKeyword: "try another Keyword",
		live: "Live",
		today: "Today",
		Updated: "Stock Availability Last Updated",
		optimizingProcurement: "Optimizing Procurement . ",
		verifiedConnectedStreamlined: "Verified, Connected, Streamlined",
		procurementManagement: "Procurement Management .",

		email: "E-mail",
		name: "Name",
		mobile: "Mobile Number",
		msg: "Message",
		nameIsRequired: "Name is required",
		mobileNumberIsRequired: "MobileNumber is required",
		messageIsRequire: "Message is require",
		yourMessageSentSuccessfully: "Your Message Sent Successfully",
		yourMessageSentnotSuccessfully: "Your Message not Sent Successfully",
		sendMessage: "Send Message",
		getInTouch: "Get in touch",
		dropUsANoteBelow: "Drop us a note below",
		valueProposition: "Value Proposition",
		transparency: "Transparency",
		contentOfTransparency:
			"There’s always a risk factor involved with evaluating and reference checking new vendors. A bird’s eye view of similar prices in the market and supplier metrics makes the decision-making process as informed as ever.",
		accountability: "Accountability",
		contentOfAcountability:
			"It’s a large market with no real central depository for contractor or supplier performance. We’re committed to delivering the best possible procurement experience to you by constantly enhancing our verified network of suppliers and intelligent dashboard tools.",
		optimizedProcess: "Optimized Process",
		contentOfoptimizedProcess:
			"The process of sourcing - evaluating - negotiating - deciding is a tedious time consuming task which often needs to be repeated several times with little supporting market intelligence. Connecting all parties through an automated platform increases reliability of the outcome while streamlining time and cost savings.",
	},
};
