export const en = {
  language: "English",
  registration: {
    register: "Register ",
    createAnAccount: "Create An Account",
    firstName: "First Name",
    lastName: "Last Name",
    mobileNumber: "Mobile Number",
    role: "Role",
    whatsAppNumber: "WhatsApp Number",
    companyName: "Company Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    work: "Work",
    description: "Description",
    country: "Country",
    government: "Government",
    address: "Address",
    companyPhoneNumber: "Company Phone Number",
    commercialRecord: "Commercial Record",
    uploadCompanyLogo: "Upload Company Logo",
    optional: "Optional",
    acceptTermsOfServiceAndPrivacyPolicy:
      "Accept Terms of Service and Privacy Policy",
    alreadyHaveAnAccount: "Already Have An Account?",
    signIn: "Sign In",
    email: "Email",
    job: "Job",
    companyMail: "Company mail",
    companyWebsite: "Company Website",
    company: "Company",
    individual: "Individual",
    buyer: "Buyer",
    Contractor: "Contractor",
  },
  footer: {
    copyRights: "2021 Shayyek. All Rights Reserved",
  },
};
