export const en = {
  language: "English",
  registration: {
    register: "Register ",
    createAnAccount: "Create An Account",
    firstName: "First Name",
    lastName: "Last Name",
    mobileNumber: "Mobile Number",
    role: "Role",
    whatsAppNumber: "WhatsApp Number",
    companyName: "Company Name",
    password: "Password",
    confirmPassword: "Confirm Password",
    work: "Work / Field",
    field: "Field",
    description: "Description",
    country: "Country",
    governorate: "Governorate",
    address: "Address",
    companyPhoneNumber: "Company Phone Number",
    commercialRegister: "Commercial Register ",
    uploadCompanyLogo: "Upload Company Logo( Optional )",
    optional: "Optional",
    acceptTermsOfServiceAndPrivacyPolicy:
      "Accept Terms of Service and Privacy Policy",
    alreadyHaveAnAccount: "Already Have An Account?",
    signIn: "Sign In",
    email: "Email",
    job: "Job",
    companyMail: "Company Mail ( Optional )",
    companyWebsite: "Company Website",
    companyWebsiteOptional: "Company Website (Optional)",
    company: "Company",
    individual: "Individual",
    buyer: "Buyer",
    Contractor: "Contractor",
    admin: "Admin",
    employee: "Employee",
    Supplier: "Supplier",
    userType: "User type",
    commercialRecordOptional: "CommercialRecord (Optional)",
    organisationLegalStructure: "Organisation Legal Structure",
    pleaseChooseCountryFirst: "please Choose Country First",
    pleaseFillAllRequiredFields: "Please fill all required fields *",
    pleaseFillFirstName: "* Please fill first name",
    pleaseFillLastName: "* Please fill last name",
    pleaseChooseCompanyName: "* Please Choose Company name",
    PleaseChooseWork: "* Please Choose Work",
    pleaseFillmobileNumber: "* Please enter valid phone number",
    pleaseFillEmail: "* please Fill Email",
    pleaseFillPassword: "* please Fill Password",
    pleaseFillConfirmPassword: "* Please Fill Confirm Password",
    pleaseChooseCompanyType: "* Please Choose Company Type",
    pleaseFillCompanyWebsite: "* Please Fill Company website",
    pleaseFillCountry: "* Please Fill Country",
    pleaseChooseGovernorate: "* Please Choose Governorate",
    pleaseFillAddress: "* Please Fill Address",
    pleaseUploadCommercialRegister: "* Please Upload Commercial Register",
    pleaseChooseYourRole: "* Please Choose Your Role  ",
    pleaseChooseYearofStartingOperation:
      "* Please Choose year of starting operation",
    pleaseFillCompanyPhoneNumber: "* Please fill company phone number",
    pleaseChooseVolumeOfBusiness: "* Please Choose Volume of Business",
    uploadValidImage: "Please upload a vaild image",
    regSuccessTitle: "Successfully Registered",
    checkMail: "Check Your Mail to Verify Your Account",
    or: "Or",
    verifyMobile: "Verify your Mobile Number",
    yearOfStartingOperation: "Year of Starting Operation",
    volumeOfBusiness: "Volume of Business",
  },
  footer: {
    copyRights: "2021 Shayyek. All Rights Reserved",
  },

  navbar: {
    signin: "Sign in",
    register: "Register",
    requestRFQ: "Request RFQ",
    cart: "Cart",
    AllSuppliers: "All Suppliers",
    admin: "Admin",
    logout: "Logout",
    viewProfile: "View Profile",
    contactUs: "Contact Us",
  },
  suppliers: {
    suppliersFilter: {
      filter: "Filter",
      category: "Category",
      location: "Location",
      products: "Products",
      all: "All",
      inStock: "In Stock",
      rate: "Rate",
    },
    rateDetails: {
      amountOfWorkOpinion: "Volume of work ?",
      paymentFacilitiesOpinion:
        "Payment terms compared to others? Do they need many payments in between?",
      relativePricesOpinion: "Prices compared to others?",
      handlingWayOpinion:
        "How was your experience? How was their service? Did they make many change-orders? ",
      timingOpinion: "Finished the job on time? Response time to requests?",
      workQualityOpinion: "Quality of work? Safety? Cleanliness? etc... ",
    },
    productName: "Product Name",
    price: "Price",
    chooseSize: "Please choose size",
    chooseModel: "Please choose model",
    items: "Items",
    inYourCart: "in your cart",
    checkOut: "Checkout",
    checkoutFor: "Checkout for",
    paymentMethod: "Payment Method",
    paymentDetails: "Payment Details",
    cardNumber: "Card Number",
    CVV: "CVV",
    name: "Name",
    expDate: "Exp.Date",
    confirmPayment: "Confirm Payment",
    willGetInTouch: "We will get on the below contact details ASAP!",
  },
  login: {
    signin: "Sign in",
    mobileNumber: "Mobile Number",
    email: "Email",
    password: "Password",
    forgetPassword: "Forget Password ?",
    didHaveAnAcount: "Didn’t Have an acount ?",
    registerNow: "Register Now !",
    signInWithMobileNumber: "Sign in With Mobile Number ?",
    signInWithMobileEmail: "Sign in With E-mail ?",
    confirmPassword: "Confirm Password",
    save: "Save",
    forgetPasswordTitle: "forget Password ",
    RememberYourPassword: "Remember Your Password?",
    send: "Send",
    emailIsRequired: "Email is required",
    passwordIsRequired: "Password is required",
    confirmPasswordIsRequired: "Confirm Password is required",
    ResetPassword: "Reset Password",
    passwordConfirmationDoesnotMatch: "Password confirmation doesn't match",
    mobileNumberIsRequired: "MobileNumber is required",
    verifyYourMailNow: "Verify your mail Now",
  },
  profilePage: {
    completedPercentage: "40% Completed",
    orderIndex: "Order Index",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    companiesInOrder: "Companies in this order",
    rateCompany: "Rate Company",
    selectSuppCont: "Select supplier or contractor to rate",
    selectSupp: "Select supplier  to rate",
    date: "Date",
    total: "Total",
    addMoreWork: "*Add More Previous Works To Verify Your Account",
    prevWork: "Previous work",
    reject: "Reject",
    accept: "Accept",
    manageCompany: "Manage your company",
    savingUpTo: "Saving up to",
    q: "Q",
    activeVendors: "Active vendors",
    newVendors: "New vendors",
    savings: "Savings",
    address: "Address",
    governorate: "Governorate",
    phoneNumber: "Phone number",
    email: "Email",
    organizLegalStruc: "Organization legal structure",
    companyWebsite: "Company website",
    commercialRegister: "Commercial register",
    myRFQs: "My RFQs",
    myOrders: "My Orders",
    projectName: "Project Name",
    compSuppName: "Company/Supplier Name",
    status: "Status",
    note: "Note",
    actionList: "Action List",
    rateNow: "Rate now",
    view: "View",
    supplierContractorName: "Supplier/Contractor name",
    buyerName: "Buyer name",
    companyName: "Company name",
    deliveryDate: "Delivery Date",
    deliveryAddress: "Delivery Address",
    acceptOffer: "Accept offer",
    cancel: "Cancel",
    name: "Name",
    type: "Type",
    workField: "Work field",
    profileInfo: "Profile Information",
    mobileNumber: "Mobile Number",
    companyEmail: "Company E-mail",
    companyLegalStructure: "Company legal structure",
    change: "Change",
    save: "Save",
    discardChanges: "Discard changes",
    changePassword: "Change password",
    oldPassword: "Old password",
    newPassword: "New password",
    requiredOldPassword: "New password is required",
    requiredNewPassword: "Old password is required",
    add: "Add",
    addPhoneNumber: "Phone number",
    changePhoneNumber: "Add phone number",
    commercialRecord: "Commercial Records",
    addWork: "Add Work",
    draft: "Draft",
    manageyourCompany: "Manage your Company",
    close: "Close",
    saveChanges: "Save changes",
    profileName: "Profile name",
    inviteToRFQ: "Invite to specific RFQ",
    see: "See",
    marketPlace: "marketplace",
    didYouWorkWith: "You have worked with",
    rateIt: "can you rate it",
    whatsapp: "WhatsApp",
    copyLink: "Copy link",
    addToFavVendors: "Add to My Favourite Vendors",
    favVendors: "My Favourite Vendors",
    deleteFavVendors: "Remove From My Favourite Vendors",
    addToMySummary: "Add to My Summary",
    addedToFavVendors: "Added to My Favourite Vendors",
  },
  offerTable: {
    name: "Name",
    company: "Company",
    price: "Price",
    city: "City",
    paymentRequired: "Payment Required",
    rating: "Rating",
    volumeOfWorkFromShyeek: "Volume of work from Shyeek",
    note: "Note",
    notes: "Notes",
    actionList: "Action List",
    delete: "Delete",
    acceptOffer: "Accept Offer",
    startConversation: "Start Conversation",
    makeOnlineSession: "Make online session",
    view: "View",
    cancel: "Cancel",
    buyerName: "Buyer Name",
    projectOwner: "Project Owner",
    projectContractor: "Project Contractor",
    projectName: "Project Name",
    projectConsultant: "Project Consultant",
    deliveryDate: "Delivery Period",
    deliveryAddress: "Delivery Address",
    QANDAWALL: "Q And A Wall",
    unitPrice: "Unit Price",
    totalPrice: "Total Price",
    itemDocuments: "Item Documents",
    uploadDocuments: "Upload Documents",
    addFile: "Add File",
    priceIncludingVAT: "The price include VAT",
    paymentTerms: "Payment Terms",
    paymentConditions: "Payment Conditions",
    projectDocuments: "Project Documents",
    offerValidity: "Offer Validity",
    yes: "Yes",
    no: "No",
    saveAsDraft: "Save as Draft",
    submit: "Submit",
    allQuotationsRecivedForThisRFQ: "All Quotations Received For This RFQ",
    hide: "Hide",
    show: "Show",
    Company: "Company",
    noAvailbleDocument: "No available document",
    vendorNotes: "Vendor Notes",
    vandorName: "Vendor Name",
    package: "Package",
    includeVat: "Include Vat",
    notIncludeVat: "Not Include Vat"
  },
  supplierHome: {
    addNewProduct: "Add New Product",
    drafts: "Drafts",
    addPriceList: "Add Price List",
    save: "Save",
    saveChanges: "Save Changes",
    discardChanges: "Discard Changes",
    cancel: "Cancel",
    pleaseUploadExcel: "Please upload an Excel sheet",
    addProductSuccess: "Your request to add product is being processed",
    ok: "Ok",
    specs: "Specs",
    saveAndAdd: "Save & Add Another",
    productName: "Product name",
    price: "Price",
    addDifferentSizes: "Add different Sizes",
    addDifferentModels: "Add different Models",
    availableQuantity: "Available Quantity in stock",
    add: "Add",
    pleaseAddPhoto: "Please add a photo",
    pleaseAddSpecs: "Please add specs",
    pleaseAddPrice: "Please add price",
    pleaseAddName: "Please add a name",
    pleaseAddQty: "Please add quantity",
    rfqInvitations: "RFQ invitations",
    noOfQuotations: "No. of quotations",
    deadline: "deadline",
    maxPrice: "Max price",
    minPrice: "Min price",
    fillSheet: "Fill Sheet",
    productDetails: "Product details",
    edit: "Edit",
    delete: "Delete",
    noRFQs: "No RFQs",
    noProducts: "There are no products",
    youCanAddProducts: "You can add products to your marketplace",
    chooseSize: "Choose size",
    chooseModel: "Choose model",
    sizes: "Sizes",
    models: "Models",
    addToCart: "Add to Cart",
    quantity: "Quantity",
    paymentTerms: "Payment terms",
    saveAsDraft: "Save as a draft",
    submit: "Submit",
    unitPrice: "Unit Price",
    totalPrice: "Total Price",
    deliveryDate: "Delivery date",
    sizeOfContract: "Size Of Contract / PQ",
    uploadDocuments: "Upload Documents",
    uploadDocumentsExample:
      "Example: Certificate of Performance / Contract / PO / Invoice etc...",
    projectNameFieldRequired: "* Project name field is required",
    descriptionFieldRequired: "* Description field required",
  },
  buyerHome: {
    importExcelFile: "Import Excel File",
    addNewItem: "Add New Item",
    addNewPackage: "Add different Package in this project",
    projectPackages: "Project Packages",
    ccCollugues: "CC Collugues",
    backToHome: "Back to home",
    item: "Item No",
    unit: "Unit",
    description: "Description",
    quantity: "Quantity",
    preferredBrands: "Preferred Brands",
    categories: "Categories",
    includeInstallation: "Include Installation",
    itemDocuments: "Item Documents",
    addFile: "Add File",
    notes: "Notes",
    selectCategory: "Select Category",
    category: "Category",
    installAll: "Install all",
    deliveredTo: "Delivered To",
    companyWarehouse: "Company warehouse",
    address: "Address",
    deadlineRecievingOffers: "Deadline recieving offers",
    deliveryDate: "Delivery date",
    confirm: "Confirm",
    selectDate: "Select Date",
    invitedByEmail: "Invited by E-mail",
    addNewEmail: "Add new E-Mail",
    publishToNetwork:
      "Publish to relevant Shayyek suppliers & contractors network",
    filterForPreQual: "Filter for pre-qualification",
    verifiedByShayyek: "Verified by Shayyek",
    relevantVolumeOfBusiness: "Relevant volume of business",
    sameVendorLocation:
      "Vendor location same city as my location or project location",
    moreThan5Years: "5+ years of experience",
    revealPrices: "Reveal prices to bidders",
    attachProjectDocument: "Attach Project Documents",
    postRFQ: "Post RFQ",
    back: "Back",
    selectSupplierEmail: "Select colleagues E-mail",
    newItemAdded: "New item added",
    projectName: "Project Name",
    typeProjectName: "Type Project Name",
    projectConsultant: "Project consultant",
    typeProjectConsultantName: "Type project consultant name",
    projectLocation: "Project Location",
    selectFromCities: "Select from Egypt cities",
    projectOwner: "Project owner",
    typeProjectOwner: "Type Project Owner Name",
    projectContractor: "Project Contractor",
    typeProjectContractorName: "Type Project Contractor Name",
    makeNotVisibleToVendors: "Make not visible to vendors",
    privateTender: "Private tender",
    publicTender: "Public tender",
    inviteByEmail: "Invite by E-Mail",
    enterEmail: "Enter Email",
    or: "Or",
    inviteByWhatsapp: "Invite by WhatsApp number",
    inviteByWhatsappNote: "You will select the numbers after posting the RFQ",
    selectFromVendors: "Select from favourite vendors",
    selectFromMyFavVendors: "Select from my favourite vendors",
    invite: "Invite",
    interestedInVolumeOfBusiness: 'I’m only interested in vendors with volume of business:',
    fillDescriptionError: "Please fill the description of all items!",
    categorySearch: 'Search in categories or sub',
    mostFrequentlyUsed: "Most frequently used",
    allCategories: "All Categories",
    addValidEmail: "Please add a valid email",
    addEmail: "Add email",
    postRFQAlert:
      "Please choose suppliers & contractors you want to share RFQ with.",
    RFQs: "RFQs",
    NoOfQuotations: "No. of quotations",
    deadline: "Deadline",
    minPrice: "Min Price",
    maxPrice: "Max Price",
    edite: "Edit",
    viewProfile: "View Profile",
    delete: "Delete",
    cancel: "Cancel",
    addRfq: "Add New RFQ",
    viewOffers: "View offers",
    noRFQs: "No RFQs",
    noCompanies: "No companies match your interests",
    toSeeCompanies: "you can edit your work/field to see related companies",
    relatedMarketPlace: "Related MarketPlace",
    confirmDeleteRow: "Are you sure you want to delete the selected row?",
    confirmDeletePackage: "Are you sure you want to delete the selected package?",
    confirmDeleteRFQ: "Are you sure you want to delete the RFQ?",
    confirmDeleteProject: "Are you sure you want to delete this project?",
    addPackageName: "Add Package Name",
    packageName: "Package Name",
    completeRFQ: "Complete RFQ",
    addPack: "Add Package",
    name: 'Name',
    addPackAlert: "Please fill all the required fields before adding new package",
    typePackageName: "Type Package Name in Project",
    submit: "Submit",
    fileError:
      "Unknown File! Please attach file in one of these extensions: ",
    ok: "OK",
    done: "Done",
    postedSuccess: "RFQ was Posted Successfully.",
    beforeSumbit: "Before submitting your RFQ",
    addAnotherPackage: "Do You Want Add Another Package?",
    addPackage: "Add Another Package",
    readyToSubmit: "Are you sure you want to submit your RFQ?",
    addNewQuestion: "Add New Question",
    addQuestion: "Add Question",
    addAnswer: "Add Answer",
    asked: "Asked",
    answered: "Answered",
    me: "Me",
    otherVendor: "Other Vendor",
  },
  home: {
    shayek: "Shayyek",
    noResultFound: "No Result Found",
    tryAnotherKeyword: "try another Keyword",
    live: "Live",
    today: "Today",
    Updated: "Stock Availability Last Updated",
    optimizingProcurement: "Optimizing Procurement . ",
    verifiedConnectedStreamlined: "Verified, Connected, Streamlined",
    procurementManagement: "Procurement Management .",

    email: "E-mail",
    name: "Name",
    mobile: "Mobile Number",
    msg: "Message",
    nameIsRequired: "Name is required",
    mobileNumberIsRequired: "MobileNumber is required",
    messageIsRequire: "Message is require",
    yourMessageSentSuccessfully: "Your Message Sent Successfully",
    yourMessageSentnotSuccessfully: "Your Message not Sent Successfully",
    sendMessage: "Send Message",
    getInTouch: "Get in touch",
    dropUsANoteBelow: "Drop us a note below",
    valueProposition: "Value Proposition",
    transparency: "Transparency",
    contentOfTransparency:
      "There’s always a risk factor involved with evaluating and reference checking new vendors. A bird’s eye view of similar prices in the market and supplier metrics makes the decision-making process as informed as ever.",
    accountability: "Accountability",
    contentOfAcountability:
      "It’s a large market with no real central depository for contractor or supplier performance. We’re committed to delivering the best possible procurement experience to you by constantly enhancing our verified network of suppliers and intelligent dashboard tools.",
    optimizedProcess: "Optimized Process",
    contentOfoptimizedProcess:
      "The process of sourcing - evaluating - negotiating - deciding is a tedious time consuming task which often needs to be repeated several times with little supporting market intelligence. Connecting all parties through an automated platform increases reliability of the outcome while streamlining time and cost savings.",
  },
  contractorHome: {
    date: "Date",
    sizeOfWork: "Size of work",
    shayyekProjects: "Shayeek Projects",
  },
  messages: {
    lastPrice: "Last Price",
    enterOfferPrice: "Enter offer percent",
    endSession: "End Session",
    endAndGiveBadge: "End & give badge",
    suppliers: "Suppliers",
    selectOnlineSessionMembers: "Select Online Session Members",
    pickOnlineSession: "Pick Online Session Time And Date",
    noMsgsFound: "No Messages Found",
    viewChat: "View Chat",
    viewProfile: "View Profile",
    deleteConversation: "Delete Conversation",
  },
  rfqSummary: {
    procSteps: "Your Procurement Steps",
    Prequalification: "Prequalification",
    technicalComparison: "Technical Comparison",
    commercialComparison: "Commercial Comparison",
    projectName: "Project Name",
    projectOwner: "Project Owner",
    projectContractor: "Project Contractor",
    projectConsultant: "Project consultant",
    deliveryDate: "Delivery Date",
    deliveryPeriod: "Delivery Period",
    deliveryAddress: "Delivery Address",
    projectPackages: "Project Packages",
    mySummary: "My Summary",
    acceptAndNotifyVendors: "Accept & Notify Vendors",
    covertToReverseAuction: "Convert To Reverse Auction",
    viewQuotation: "View Quotation",
    AddToMySummary: "Add To My Summary",
    vendorNotes: "Vendor notes",
  },
  reverseAuction: {
    selectMembers: 'Select Reverse Auction Members',
    meetingTime: "Meeting Time",
    reverseAuctionFor: 'This Reverse Auction is for',
    allItems: "All Items in RFQ",
    selectSomeItems: "Select Some Items in RFQ",
    anyNotes: "Any other notes you would like to clarify for participants:",
    submit: "Submit",
    selectSomeItemss: "Select Some Items in RFQ:",
    ok: "Ok"
  }
};
